[project]
name = "utw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "John Chase", email = "johnhchase@protonmail.com" }]
requires-python = ">=3.12"

dependencies = [
    "pytest",
    "pytest-cov",
    "pandas",
    "coverage>=7.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
